language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t akashhudge-git/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akashhudge-git/docker-react npm run test
